version: "3.9"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: 'studies-search_backend_container'
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-127.0.0.1}
      - SECRET_KEY=${SECRET_KEY}
      - ADMINS=${ADMINS}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST:-127.0.0.1}
      - DATABASE_URL=postgres://user:password@database/studies-search
      - GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE=${GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      - database
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - '${SSB_HOST_PORT:-8000}:8000'
    command: [ 'sh', '/usr/src/app/entrypoint.sh' ]
    restart: always
  database:
    image: "postgres:15-alpine"
    container_name: "studies-search_postgresql_container"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=studies-search
    volumes:
      - ./postgresql/mount/:/var/lib/postgresql/data
    restart: always

# docker compose up --build --detach