FROM python:3.10-alpine

WORKDIR /usr/src/app

ENV DEBUG False
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY Pipfile Pipfile.lock ./
RUN apk update
RUN apk add git
RUN python -m pip install --upgrade pip
RUN pip install pipenv && pipenv install --ignore-pipfile --deploy --system

COPY . ./

EXPOSE 8000

CMD ['gunicorn', '--bind', '0.0.0.0:8000' 'backendApi.wsgi']