version: '3.9'
services:
  frontend:
    image: 'ghcr.io/dominikjalowiecki/studies-search_frontend:latest'
    container_name: 'studies-search_frontend_container'
    ports:
      - '${SSF_HOST_PORT:-80}:80'
    depends_on:
      - backend
    restart: always
  backend:
    image: 'ghcr.io/dominikjalowiecki/studies-search_backend:latest'
    container_name: 'studies-search_backend_container'
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-127.0.0.1}
      - SECRET_KEY=${SECRET_KEY}
      - ADMINS=${ADMINS}
      - SCRIPT_NAME=${SCRIPT_NAME:-}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST:-http://localhost}
      - DATABASE_URL=postgres://user:password@database/studies-search
      - GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE=/run/secrets/google_service_account
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    secrets:
      google_service_account:
        file: ./studies-search-service-account.json
    depends_on:
      - database
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - '${SSB_HOST_PORT:-8000}:8000'
    command: ['sh', '/usr/src/app/entrypoint.sh']
    restart: always
  database:
    image: 'postgres:15-alpine'
    container_name: 'studies-search_postgresql_container'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=studies-search
    volumes:
      - ./postgresql/mount/:/var/lib/postgresql/data
    restart: always
