# Generated by Django 4.2.3 on 2024-01-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studiesSearchApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='studiesSearchApi.membership'),
        ),
    ]
